### ISSUE TITLE
Tests don't work with minimal configuration helm install due to default model.name in values.yaml

### ISSUE THREAD

**Issue by jmineroff** [NVIDIA/nim-deploy#14]
I didn't use a custom values file to do the install, but got stuck trying to figure out why the test command was failing. It turns out it was due to the default model.name not matching the name of the default model (llama3-8b-instruct).

Can you either change the default model.name value or add --set model.name='llama3-8b-instruct' to the minimal command?

**Comment by supertetelman** [comment]
This is a good suggestion, thank you.
