### ISSUE TITLE
Unable to deploy NIM via KServe

### ISSUE THREAD

**Issue by Syulin7** [NVIDIA/nim-deploy#16]
When deploying NIM via KServe, KServe sets the mounted PVC to read-only, which will cause the model download to fail.
```
    - mountPath: /mnt/models
      name: kserve-pvc-source
      readOnly: true
```
error:
```
ADDITIONAL INFORMATION: Meta Llama 3 Community License, Built with Meta Llama 3.
A copy of the Llama 3 license can be found under /opt/nim/MODEL_LICENSE.
Traceback (most recent call last):
  File "/usr/local/bin/nim-llm-check-cache-env", line 8, in <module>
    sys.exit(check_cache_dir())
  File "/usr/local/lib/python3.10/dist-packages/vllm_nvext/utils/caches.py", line 29, in check_cache_dir
    raise RuntimeError(f"Unable to write to NIM_CACHE_PATH ({cache_path})")
RuntimeError: Unable to write to NIM_CACHE_PATH (/mnt/models/cache)
```

**Comment by Syulin7** [comment]
https://github.com/kserve/kserve/issues/3687

Currently the implementation for PVC model stores [here](https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L255) expects that a PV containing model files is always mounted to a ServingRuntime as ReadOnly.

**Comment by supertetelman** [comment]
Yes, I noted this in the updated documentation.

Working with the KServe community to add a RW version here and we are considering improving the docs on cache creation and creating an init container or some other mechanism to pre-download the models.
