### ISSUE TITLE
How to select a specific profile?

### ISSUE THREAD

**Issue by bronzafa** [NVIDIA/nim-deploy#17]
When we deploy the Helm it automatically select the model profile based on the best config for the model/number of GPUs, on docker we can use the -e NIM_MODEL_PROFILE=<id_of_the_profile> to select a different one, but I couldn't find where to set this on the Helm chart.

**Comment by supertetelman** [comment]
You can still set that same environment variable using the `env` field of the values.yaml.

**Comment by bronzafa** [comment]
can you provide an example? I couldn't find the right place to add it and my tests was not successful.
