### ISSUE TITLE
Does NIM support deployment of models other than the Llama 3 family?

### ISSUE THREAD

**Issue by AbdurNawaz** [NVIDIA/nim-deploy#19]
Does NIM support deployment of models other than the Llama 3 family?

**Comment by supertetelman** [comment]
This deployment repo is showcasing the NIMs that have been released as generally available. The up-to-date support list of those NIMs can be found here https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#supported-models.

Currently this list does not include all the other NIMs that are not yet GA which can be explored in more detail on https://build.nvidia.com/.

Over the coming months I would expect to see the support matrix and examples in this repo to grow to include more NIMs beyond the two Llama models.
