### ISSUE TITLE
List of Nvidia Nim available/released LLM Models 

### ISSUE THREAD

**Issue by nskumz** [NVIDIA/nim-deploy#34]
could you please list out the available nvidia nim LLM model images as of now. 
so that we can work around those models apart form these two
1. meta-llama/Meta-Llama-3-70B-Instruct
2. meta-llama/Meta-Llama-3-8B-Instruct

**Comment by supertetelman** [comment]
A full list of supported LLM NIM models can be found here: https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#supported-models

Additional NIM models for things like reranking and embedding can also be found on the nvidia docs page and on https://build.nvidia.com/.

The current list:

[Llama 3.1 8B Base](https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#llama-3-1-8b-base)
[Llama 3.1 8B Instruct](https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#llama-3-1-8b-instruct)
[Llama 3.1 70B Instruct](https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#llama-3-1-70b-instruct)
[Meta-Llama-3-8B-Instruct](https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#meta-llama-3-8b-instruct)
[Meta-Llama-3-70B-Instruct](https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#meta-llama-3-70b-instruct)
[Mistral-7B-Instruct-v0.3](https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#mistral-7b-instruct-v0-3)
[Mixtral-8x7B-v0.1](https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#mixtral-8x7b-v0-1)
[Mixtral-8x22B-v0.1](https://docs.nvidia.com/nim/large-language-models/latest/support-matrix.html#mixtral-8x22b-v0-1)
