### ISSUE TITLE
Auth issue during container pull

### ISSUE THREAD

**Issue by edesalve** [NVIDIA/nim-deploy#42]
Hi all. I'm trying to deploy `llama3-8b-instruct` with helm chart.

### System Info

- OS: Ubuntu 22.04
- k8s version: 1.30

### Description
I get a very strange problem, here the events from pod description:

```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  28m                  default-scheduler  Successfully assigned nim/llama3-8b-instruct-775875c8db-7r2kz to s2eworker1
  Warning  Failed     2m41s                kubelet            Failed to pull image "nvcr.io/nim/meta/llama3-8b-instruct:1.0.0": failed to pull and unpack image "nvcr.io/nim/meta/llama3-8b-instruct:1.0.0": failed to copy: httpReadSeeker: failed open: server message: insufficient_scope: authorization failed
  Warning  Failed     2m41s                kubelet            Error: ErrImagePull
  Normal   BackOff    2m40s                kubelet            Back-off pulling image "nvcr.io/nim/meta/llama3-8b-instruct:1.0.0"
  Warning  Failed     2m40s                kubelet            Error: ImagePullBackOff
  Normal   Pulling    2m25s (x2 over 28m)  kubelet            Pulling image "nvcr.io/nim/meta/llama3-8b-instruct:1.0.0"
```

The behavior is very strange, as monitoring the worker node, the container pull effectively starts (I see the memory go down on the worker), but somehow at the end of the pull operation something goes wrong.

Credentials should be correctly set and I successfully pull the container from nvcr.io with them.

**Comment by supertetelman** [comment]
There may have been some issues with nvcr.io during the time you were pulling this container. Can you try again?

**Comment by edesalve** [comment]
@supertetelman I believe that the issue is someway related to the very slow internet connection. I found on k8s forum [this](https://discuss.kubernetes.io/t/error-when-pulling-large-image-5gb/25714) post regarding the same issue.
I currently get around the problem by pulling the image from a worker and using a persistent volume. Unfortunately at present I cannot reproduce the issue on similar infrastructure (vmware vm + k8s) with better internet connection.

**Comment by JackMcCabeLothbrok** [comment]
I am having the same problem.  I have tried everything.   Did you find a solution?

It may be an issue with containerd.  I can pull the images using Docker, but when using ContainerD I have issues.
